services:
  product-service:
    build: ./product-service
    ports: 
      - "${PRODUCT_SERVICE_PORT}:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=${PRODUCT_DB_HOST}
      - DB_NAME=${PRODUCT_DB_NAME}
      - DB_USER=${PRODUCT_DB_USER}
      - DB_PASSWORD=${PRODUCT_DB_PASSWORD}
    container_name: product-services
    restart: always
    depends_on:
      product-db:
        condition: service_healthy

  
  # product-db:
  #   image: mysql:latest
  #   env_file:
  #     - .env
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${PRODUCT_DB_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${PRODUCT_DB_NAME}
  #   volumes:
  #     - product-db-data:/var/lib/mysql

  product-db:
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${PRODUCT_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PRODUCT_DB_NAME}
    volumes:
      - product-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  cart-service:
    build: ./cart-service
    ports:
      - "8000:8000"
    container_name: cart-service
    restart: always

  review-service:
    build: ./review-service
    ports:
      - "5002:5002"
    container_name: review-service
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: product-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - product-db
    container_name: phpmyadmin
    restart: always

volumes:
  product-db-data: