services:
  product-service:
    build: ./product-service
    ports:
      - "3000:3000"
    container_name: product_service
    restart: always

  cart-service:
    build: ./cart-service
    ports:
      - "8000:8000"
    container_name: cart_service
    restart: always

  review-service:
    build: ./review-service
    ports:
      - "5002:5002"
    container_name: review_service
    restart: always
  
  user-service:
    build: ./user-service
    ports:
     - "4000:4000"
    container_name: user_service
    restart: always
